import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <title>Base64 to PDF Converter</title>
        <meta name="description" content="Convert base64 strings to PDF and vice versa with our easy-to-use online tool." />
        <meta name="keywords" content="base64 to pdf, pdf to base64, online converter, download pdf, view pdf" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />
        <meta property="og:title" content="Base64 to PDF Converter" />
        <meta property="og:description" content="Convert base64 strings to PDF and vice versa with our easy-to-use online tool." />
        <meta property="og:url" content="https://pdf-app-livid.vercel.app/" />
        <meta property="og:type" content="website" />
        <link rel="icon" href="/favicon.ico" />
       </head>
      <body className={inter.className}>          
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          </body>
    </html>
  );
}
